import { Syne } from "next/font/google";
import "./globals.css";
import Providers from "../GlobalRedux/provider";
import ToastProvider from "../components/providers/toast-providers";
import Script from "next/script";

const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Codding Commando",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={syne.className}>
          <Providers>
            <ToastProvider />
            <main>{children}</main>
          </Providers>
        </body>
      </html>
      <Script src="https://checkout.razorpay.com/v1/checkout.js" />
    </>
  );
}
